export const bod = [
  {
    name: "Shri. Balasaheb Bhausaheb Thorat",
    position: "President",
    age: 64,
    src: "/about/bbb.jpg",
    facebook: "facebook",
    twitter: "twitter",
    linkedin: "linkedin",
  },
  {
    name: "Shri. Keruji Haruji Gunjan Patil",
    position: "Vice President",
    age: 87,
    facebook: "facebook",
    twitter: "twitter",
    linkedin: "linkedin",
  },
  {
    name: "Shri. Bajirao Khandu Khemna",
    position: "Trustee",
    age: 81,
    facebook: "facebook",
    twitter: "twitter",
    linkedin: "linkedin",
  },
  {
    name: "Shri.Laxmanrao Balaji Kute",
    position: "Trustee",
    age: 67,
    facebook: "facebook",
    twitter: "twitter",
    linkedin: "linkedin",
  },
  {
    name: "Dr. Sudhir Bhaskarrao Tambe",
    position: "Trustee",
    age: 62,
    facebook: "facebook",
    twitter: "twitter",
    linkedin: "linkedin",
  },
  {
    name: "Shri. Ramnath Bhaurao Sonawane",
    position: "Trustee",
    age: 72,
    facebook: "facebook",
    twitter: "twitter",
    linkedin: "linkedin",
  },
  {
    name: "Shri Tulshiram Prabhakar Bhor",
    position: "Trustee",
    age: 62,
    facebook: "facebook",
    twitter: "twitter",
    linkedin: "linkedin",
  },

  {
    name: "Sou. Sharayu Ranjeet Deshmukh",
    position: "Trustee",
    age: 36,
    facebook: "facebook",
    twitter: "twitter",
    linkedin: "linkedin",
  },

  {
    name: "Shri Madhav Karbhari Chaudhari",
    position: "Trustee",
    age: 69,
    facebook: "facebook",
    twitter: "twitter",
    linkedin: "linkedin",
  },
];
